### ISSUE TITLE
Operator ">>" not supported for types "ELB" and "list[EC2]"

### ISSUE THREAD

**Issue by tombohub** [mingrammer/diagrams#1029]
This example:

```python
from diagrams import Diagram
from diagrams.aws.compute import EC2
from diagrams.aws.database import RDS
from diagrams.aws.network import ELB

with Diagram("Grouped Workers", show=False, direction="TB"):
    ELB("lb") >> [EC2("worker1"),
                  EC2("worker2"),
                  EC2("worker3"),
                  EC2("worker4"),
                  EC2("worker5")] >> RDS("events")
```

Causes pylance error:

```
Operator ">>" not supported for types "ELB" and "list[EC2]"
```

![image](https://github.com/user-attachments/assets/64a4c1d8-51cc-4631-a1c4-705b82f9ca30)

**Comment by tvqphuoc01** [comment]
Hi @tombohub thanks for reporting this for us we will take a look on this. 😄

**Comment by filipeaaoliveira** [comment]
Hi @tombohub @tvqphuoc01 

This does raise a concern with Pylance, because indeed the expression is not assigned to any variable, however, in the context of our library, this is intentional because the purpose of the expression is to define the relationships and flow within the diagram.

We can try to work with the Pylance team, to see if we can have an exception for our use case, but I don't know if that is possible.

**Comment by tombohub** [comment]
Hi @filipeaaoliveira, ok
