### ISSUE TITLE
Can't import module

### ISSUE THREAD

**Issue by OperationalFallacy** [mingrammer/diagrams#246]
Hi,

Trying to understand where it broke, I was using package few weeks ago and then started getting ModuleNotFoundError

```
from diagrams.oci.edge import Emaildelivery as email
```

```
python p.py
ModuleNotFoundError: No module named 'diagrams.oci.edge'
```

packages
```
pip list 
contextvars (2.4)
diagrams (0.16.0)
graphviz (0.13.2)
immutables (0.14)
Jinja2 (2.11.2)
MarkupSafe (1.1.1)
pip (9.0.3)
setuptools (39.0.1)
```

virtual env with 3.6.5

Any ideas?

**Comment by mingrammer** [comment]
Since diagrams 0.16.0, there are some breaking changes for OCI provider: https://github.com/mingrammer/diagrams/blob/master/CHANGELOG.md#oci

You should fix the `from diagrams.oci.edge import Emaildelivery as email` to `from diagrams.oci.monitoring import Email`. Sorry for the inconvenience. 

Thank you.
