### ISSUE TITLE
How to install from git repo?

### ISSUE THREAD

**Issue by mdavis-xyz** [mingrammer/diagrams#513]
I want to make a contribution by adding a new icon. Before creating a pull request, I want to test that it works. To do that I need to run the code from my branch.

I `git clone`d. Now `pip install ./` doesn't work, because there's no `setup.py` file in `/` or `/diagrams`.

How am I supposed to install this? How is the pypi package created, if not from the git repo?

**Comment by gabriel-tessier** [comment]
Hi @mdavis-xyz 

Thanks for your "future" contribution, you can test easily your added icon by using docker check how to use in https://github.com/mingrammer/diagrams/blob/master/DEVELOPMENT.md 
Usually I test this way and it's far more easy if you used to work with docker.

Other solution you can build your package and as you notice there's no setup.py because it use poetry.
More details about here: https://python-poetry.org/

Other solution and the far more easy one is following the instructions from this file https://github.com/mingrammer/diagrams/blob/master/CONTRIBUTING.md
If you just add the icon, then you run autogen.sh and there's no errors it's ok you can push your PR!

If you want to add a personal icon that not exist and use it with the actual version consider using Custom: 
https://diagrams.mingrammer.com/docs/nodes/custom

**Comment by mdavis-xyz** [comment]
Ah, I looked at `CONTRIBUTING` but not `DEVELOPMENT.md`.


Also, I just realised that the icon I wanted to add is already in the library, but in a different section to what I expected, so I didn't find it.
